name: bounds-checking
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  bounds-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: 'latest'
    - name: Update cabal package database
      run: cabal update
    - uses: actions/cache@v4
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-latest
    - name: Test
      run: cabal test --ghc-options='-fcheck-prim-bounds -fno-ignore-asserts'
